export const DEFAULT_OUTDIR = 'dist';
export const DEFAULT_ENTRY_POINT = 'malita.tsx';
export const DEFAULT_TEMPLATE= '.malita';
export const DEFAULT_GLOBAL_LAYOUTS = 'layouts/index.tsx';
export const DEFAULT_FRAMEWORK_NAME = 'malita';
export const DEFAULT_PLATFORM = 'browser';
export const DEFAULT_HOST = '127.0.0.1';
export const DEFAULT_PORT = 8888;
export const DEFAULT_BUILD_PORT = 6677;
